In [10]:
import numpy as np
a = np.arange(15, 4, -2)
print(a)
print(a[6:0:-2])
# even though we are starting with index 6 but the array contains only 5 elements it doesn't give any error

[15 13 11  9  7  5]
[ 5  9 13]


In [16]:
l1 = [1,2,3,4]
l2 = [5,6,7,8, 10]
print(l1 + l2)

[1, 2, 3, 4, 5, 6, 7, 8, 10]


In [14]:
l1 = np.array([1,2,3,4])
l2 = np.array([5,6,7,8])
print(l1 + l2)

[ 6  8 10 12]


In [20]:
l1 = np.array([[1,2,3,4], [9,8,7,6]])
l2 = np.array([5,6,7,8])
print(l1 + l2)

[[ 6  8 10 12]
 [14 14 14 14]]


In [22]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10],[20]])
print(a+b)

[[11 12 13]
 [24 25 26]]
