In [10]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
arr3 = np.concatenate((arr1,arr2), axis=0)
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# To concatenate:
# 1. Check Shape, if we are concatinating vertically we need columns to be same and if concatinating horizontally we need no. of 
#    rows to be same

In [22]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
arr3 = np.concatenate((arr1,arr2.T), axis=1)
print(arr3)

[[1 2 5]
 [3 4 6]]


In [24]:
# Flattening occurs if axis=None
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
arr3 = np.concatenate((arr1,arr2.T), axis=None)
print(arr3)

[1 2 3 4 5 6]


In [26]:
arr6 = np.array([1,2,3])
arr7 = np.array([4,5,6])
arr8 = np.hstack((arr6,arr7))
print(arr8)
# In 1D array, hstack works same as concatenation 

[1 2 3 4 5 6]


In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.hstack((a,b))
print(c)
# Whenever we do hstack, no. of columns increases and rows remain same

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
a = np.array([[1],[2],[3]]) # (3,1)
b = np.array([[4],[5],[6]]) # (3,1)
c = np.hstack((a,b))        # (3,2)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
a = np.array([1,2,3]) # (3,) --> (1,3)
b = np.array([4,5,6]) # (3,) --> (1,3)
c = np.vstack((a,b))  # (2,3) --> (2,3)
print(c)
# Broacasting occured
# Broadcasting is possible only in vtsack not hstack

[[1 2 3]
 [4 5 6]]


In [46]:
a = np.array([[1],[2],[3]]) # (3,1)
b = np.array([[4],[5],[6]]) # (3,1)
c = np.vstack((a,b))        # (6,1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
