In [12]:
import numpy as np
ar_1 = np.arange(24.0).reshape(4, 6)
print(ar_1)
print(np.hsplit(ar_1, 2), end = "\n\n")
print(np.hsplit(ar_1, 3), end = "\n\n")

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[array([[ 0.,  1.,  2.],
       [ 6.,  7.,  8.],
       [12., 13., 14.],
       [18., 19., 20.]]), array([[ 3.,  4.,  5.],
       [ 9., 10., 11.],
       [15., 16., 17.],
       [21., 22., 23.]])]

[array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.]]), array([[ 2.,  3.],
       [ 8.,  9.],
       [14., 15.],
       [20., 21.]]), array([[ 4.,  5.],
       [10., 11.],
       [16., 17.],
       [22., 23.]])]



In [22]:
arr2 = np.arange(8)
print(np.split(arr2,2))

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]


In [24]:
arr2 = np.arange(8)
print(np.split(arr2,(2,4)))

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7])]


In [26]:
arr3 = np.arange(16).reshape(4,4)
print(np.split(arr3,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [32]:
arr3 = np.arange(16).reshape(4,4)
print(np.split(arr3,2, axis=1))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
