In [10]:
a = 10
b = 10
print(a == b)
print(a is b)


True
True


In [14]:
l1 = [i for i in range(10)]
print(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
l1 = [i for i in range(10)]
l2 = list(filter(lambda x: x % 2 == 1, l1))
print(l2)

[1, 3, 5, 7, 9]


In [20]:
l3 = list(map(lambda x: x ** 2, l2))
print(l3)


[1, 9, 25, 49, 81]


In [30]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50], dtype = float)
print(arr)


[10. 20. 30. 40. 50.]


In [32]:
arr2 = np.array([[10, 20], [100, 90]])
print(arr2)

[[ 10  20]
 [100  90]]


In [36]:
arr_0= np.zeros((3,4))
print(arr_0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
arr_ones = np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
arr = np.arange(2, 15, 3)
print(arr)

[ 2  5  8 11 14]


In [42]:
ar_12 = np.array([np.arange(21, 10, -2), np.arange(10, -1, -2), np.zeros(6, dtype = np.int64)])
print(ar_12)
print("ar_12[0, 0] =",ar_12[0, 0]) # 21
print("ar_12[-1,- 2] =",ar_12[-1,- 2]) # 0
print("ar_12[0, 0:6:2] =",ar_12[0, 0:6:2]) #[21 17 13]
print("ar_12[1:2, 5:0:-2] =",ar_12[1:2, 5:0:-2]) #[[0 4 8]]
print("ar_12[-2::-1, -3:-1] =",ar_12[-2::-1, -3:-1]) #[[ 4  2] [15 13]]

[[21 19 17 15 13 11]
 [10  8  6  4  2  0]
 [ 0  0  0  0  0  0]]
ar_12[0, 0] = 21
ar_12[-1,- 2] = 0
ar_12[0, 0:6:2] = [21 17 13]
ar_12[1:2, 5:0:-2] = [[0 4 8]]
ar_12[-2::-1, -3:-1] = [[ 4  2]
 [15 13]]


In [44]:
arr = np.array([np.arange(21,10,-2), np.arange(10,-1,-2), np.zeros(6, dtype = np.int64)])
print(arr)

[[21 19 17 15 13 11]
 [10  8  6  4  2  0]
 [ 0  0  0  0  0  0]]


In [50]:
print(arr[-2::-1, -3:-1])

[[ 4  2]
 [15 13]]
