In [4]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

1.26.4
2.2.2


In [2]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

2.3.1
2.3.0


In [12]:
ar_1 = np.array([10,20,30])
l = [1,2,3]
print(ar_1)
print(l)

[10 20 30]
[1, 2, 3]


In [16]:
ar_1 = np.array([10,20,30])
ar_2 = np.array([10,20,30], dtype = float)
l = [1,2,3]
print(ar_1)
print(ar_2)
print(l)

[10 20 30]
[10. 20. 30.]
[1, 2, 3]


In [18]:
ar_1 = np.array([10,20,30,"a"])
ar_2 = np.array([10,20,30], dtype = float)
l = [1,2,3]
print(ar_1)
print(ar_2)
print(l)

['10' '20' '30' 'a']
[10. 20. 30.]
[1, 2, 3]


In [26]:
ar_3 = np.zeros(3, dtype = int)
print(ar_3)

[0 0 0]


In [34]:
ar_3 = np.zeros(3)
ar_4 = np.zeros((3,3))
print(ar_3)
print(ar_4)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = [
    [1,2],
    [3,4],
    [5,6]
]
arr2 = [
    [[1,2],[3,4],[5,6]],
    [[1,2],[3,4],[5,6]]
]

In [36]:
ar_5 = np.ones(3)
ar_6 = np.ones((3,3))
print(ar_5)
print(ar_6)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
arr = np.arange(1,10,2)
arr1 = np.arange(5)
print(arr, arr.ndim)
print(arr1)

[1 3 5 7 9] 1
[0 1 2 3 4]


In [46]:
arr = np.array(10)
print(arr)

10


In [72]:
arr = np.ones((2,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)
6
float64
8


In [66]:
ar_1 = np.array([10,20,30,'a'])
print(ar_1.shape)
print(ar_1.dtype)

(4,)
<U21
